/* =================================================================================
   TYPES — JSDoc typedefs for the DB⇄app boundary.

   WHY THIS FILE IS .js AND NOT .ts / .d.ts
   ----------------------------------------
   `tailwind.config.js` globs src recursively for `.js`/`.jsx` ONLY. A `.ts`/`.tsx` file is
   INVISIBLE to
   that glob, so any class name living in one is never emitted into the CSS — the file
   compiles, the build exits 0, and the UI renders UNSTYLED. That failure is silent, which
   makes it exactly the kind of trap this safety net exists to prevent. So: no renames, no
   TypeScript source files, types expressed as JSDoc only.

   This module has NO runtime value. It is imported in type position only
   (`@type {import('./types.js').Task}`), which TypeScript resolves and the bundler never
   sees — so it adds zero bytes to the bundle. The `export {}` exists solely to make it a
   module rather than a global script.

   TWO SHAPES, ALWAYS
   ------------------
   Every table has a `*Row` typedef (DB shape, snake_case, what PostgREST returns) and an
   app typedef (camelCase, what the UI consumes). `sanitize.js` is the only sanctioned
   crossing between them. If you find yourself reading `row.workspace_id` outside
   sanitize.js, that is the bug.

   ID DISCIPLINE — the bug class this file exists to catch
   ------------------------------------------------------
   Not every id in this schema is a UUID, and mixing them up is a REAL failure mode that
   reaches Postgres as `22P02 invalid input syntax for type uuid`:

     - `tasks.id`     is **TEXT**, client-generated by `uid()` (e.g. "k3j4h5g6abcd").
                      So are `comments.task_id` and `notifications.task_id`, which FK to it.
     - `projects.id`  is **TEXT** too — a slug ("personal", "other") or a `uid()`.
     - Everything that references an auth user or a workspace IS a real UUID:
       `workspace_id`, `assignee_id`, `created_by`, `sender_id`, `recipient_id`,
       `members.id`, `user_id`.

   `Uuid` is therefore a BRANDED type: a plain `string` is not assignable to it. Values
   genuinely arriving from the DB are typed `Uuid` by the `*Row` typedefs, so they flow
   without friction. For the handful of true boundaries where an external `string` is known
   to be a UUID (a Supabase session id, a router param), use `asUuid()` below — and only there.

   ⚠ HOW MUCH THE BRAND ACTUALLY BUYS TODAY — measured, not assumed.
   It only constrains assignments in code TypeScript is checking AND whose values are typed.
   `src/lib/api.js` currently declares no `@param` types, so every parameter there is
   implicitly `any`, and `any` is assignable to `Uuid` — meaning `tasks.create`'s
   `row.workspace_id = workspaceId` is NOT checked. Verified by probe: assigning an untyped
   parameter to a `Uuid` field raises nothing, while assigning a known `string` raises TS2322.
   So right now the brand fires inside `sanitize.js` and at any annotated boundary, and NOT
   at the api.js call sites.

   That gap is covered two other ways, deliberately: the runtime assertion in
   `src/test/tasks.test.jsx` ("id discipline") checks a real create call, and the brand
   starts biting the api.js boundary as `@param` annotations are added — which is Phase B
   work, alongside `// @ts-check` on each extracted module. Do not describe this as
   compile-time-proof until those annotations exist.
================================================================================= */

/**
 * A real Postgres `uuid`. Branded so a plain string (notably a `uid()` output) cannot be
 * assigned to one by accident. See the ID DISCIPLINE note above.
 * @typedef {string & { readonly __uuid: unique symbol }} Uuid
 */

/**
 * A `tasks.id` — TEXT, client-generated by `uid()`, NOT a uuid. Also the type of
 * `comments.task_id` and `notifications.task_id`.
 * @typedef {string} TaskId
 */

/**
 * A `projects.id` — TEXT: either a seed slug ("personal", "other") or a `uid()`.
 * NOTE: `tasks.project` holds this value as FREE TEXT with **no FK**, so a project id can
 * dangle after a delete. The UI resolves it with `projects.find(...)` and degrades to no
 * chip rather than crashing. Do not assume it resolves.
 * @typedef {string} ProjectId
 */

/**
 * Assert at a true boundary that a string is a UUID. This is a TYPE assertion with no
 * runtime check — use it ONLY where the value provably comes from Postgres or Supabase
 * Auth (a session user id, an RPC return, a row column). Never use it to launder a
 * `uid()`; that is the exact bug the brand exists to catch.
 * @param {string} s
 * @returns {Uuid}
 */
export const asUuid = (s) => /** @type {Uuid} */ (/** @type {unknown} */ (s));

/**
 * An ISO-8601 timestamp string, as PostgREST returns `timestamptz`.
 * @typedef {string} IsoTimestamp
 */

/* ---------------------------------------------------------------------------------
   ENUMS — mirror the DB CHECK constraints. Keep these in sync with the migrations;
   a value outside these sets is rejected server-side.
--------------------------------------------------------------------------------- */

/**
 * The four-rung per-workspace ladder (owner 3 · admin 2 · member 1 · guest 0). This is
 * `workspace_members.role` — the AUTHORITY for authorization. The global `members.role`
 * is vestigial and must never be read for authz.
 * @typedef {'owner' | 'admin' | 'member' | 'guest'} Role
 */

/** @typedef {'inbox' | 'must' | 'should' | 'waiting' | 'scheduled' | 'done'} TaskStatus */
/** @typedef {'critical' | 'high' | 'medium' | 'low'} TaskPriority */
/** @typedef {'quick' | 'medium' | 'deep'} TaskEffort */

/**
 * Visibility, INDEPENDENT of assignment since Phase 2A (the legacy `owner` weld is gone).
 * `workspace` = shared; `private` = creator OR assignee only.
 * @typedef {'workspace' | 'private'} TaskPrivacy
 */

/**
 * The `invitations_status_check` CHECK is exactly these three. **There is no 'expired'
 * status** — expiry is expressed by `expires_at` passing, while `status` stays 'pending'.
 * A row is never written with 'expired', so branching on it is dead code.
 * @typedef {'pending' | 'accepted' | 'revoked'} InvitationStatus
 */

/* ---------------------------------------------------------------------------------
   TASKS
--------------------------------------------------------------------------------- */

/**
 * A subtask inside the `subtasks` jsonb column.
 * @typedef {object} Subtask
 * @property {string} id
 * @property {string} title
 * @property {boolean} done
 */

/**
 * A link inside the `links` jsonb column. `url` is scheme-allowlisted by
 * `sanitize.safeLinkUrl` on both the read and write paths; a rejected scheme becomes `''`.
 * @typedef {object} TaskLink
 * @property {string} url
 * @property {string} label
 */

/**
 * `public.tasks` as PostgREST returns it.
 *
 * Nullability below is transcribed from the actual `create table public.tasks` in
 * `supabase/migrations/00000000000000_baseline.sql` — NOT guessed. Several columns that
 * "look" optional are `not null default …`, which means they are always present on a read
 * even though a write may omit them. Keep this in sync with the baseline; a divergence here
 * is what makes a null-guard look unnecessary right before it is needed.
 *
 * @typedef {object} TaskRow
 * @property {TaskId} id                       TEXT, client-generated — NOT a uuid.
 * @property {Uuid} workspace_id               NOT NULL since Phase 2.
 * @property {string} title                    NOT NULL.
 * @property {string | null} description       Nullable (default '', but no NOT NULL).
 * @property {Uuid | null} assignee_id         Nullable — null = unassigned.
 * @property {TaskPrivacy} privacy             NOT NULL.
 * @property {ProjectId} project               NOT NULL, free text, no FK — may not resolve.
 * @property {TaskStatus} status               NOT NULL.
 * @property {TaskPriority} priority           NOT NULL.
 * @property {TaskEffort} effort               NOT NULL.
 * @property {boolean} urgent                  NOT NULL.
 * @property {boolean} important               NOT NULL.
 * @property {boolean} blocked                 NOT NULL.
 * @property {string | null} blocked_reason    Nullable.
 * @property {string | null} due_date          Nullable.
 * @property {string | null} scheduled_date    Nullable.
 * @property {number} estimated_minutes        NOT NULL, default 30.
 * @property {string[]} tags                   NOT NULL jsonb, default [].
 * @property {Subtask[]} subtasks              NOT NULL jsonb, default [].
 * @property {TaskLink[]} links                NOT NULL jsonb, default [].
 * @property {unknown} recurring               Nullable. Round-trip only; UI removed 2026-07-19.
 * @property {Uuid | null} created_by          Nullable FK to auth.users.
 * @property {IsoTimestamp} created_at         NOT NULL.
 * @property {IsoTimestamp} updated_at         NOT NULL — do not null-guard this one.
 * @property {IsoTimestamp | null} completed_at Nullable.
 * @property {number} task_order               NOT NULL bigint.
 * @property {string | null} [due_reminder_stage]
 */

/**
 * A task in app shape. Produced by `fromDbTask` / `sanitizeTask`.
 * @typedef {object} Task
 * @property {TaskId} id
 * @property {Uuid} [workspaceId]              Absent on a freshly sanitized (not yet persisted) task.
 * @property {string} title
 * @property {string} description
 * @property {Uuid | null} assigneeId
 * @property {TaskPrivacy} privacy
 * @property {ProjectId} project
 * @property {TaskStatus} status
 * @property {TaskPriority} priority
 * @property {TaskEffort} effort
 * @property {boolean} urgent
 * @property {boolean} important
 * @property {boolean} blocked
 * @property {string} blockedReason
 * @property {string | null} dueDate
 * @property {string | null} scheduledDate
 * @property {number} estimatedMinutes        Never null: the column is NOT NULL (default 30),
 *   `sanitizeTask` defaults it to 30, and both UI writes set a number. Do not widen to
 *   `number | null` — writing null would be a 23502 on a NOT NULL column.
 * @property {string[]} tags
 * @property {Subtask[]} subtasks
 * @property {TaskLink[]} links
 * @property {unknown} recurring
 * @property {Uuid | null} createdBy
 * @property {IsoTimestamp} createdAt
 * @property {IsoTimestamp} updatedAt
 * @property {IsoTimestamp | null} completedAt
 * @property {number} order
 */

/**
 * The DB-shaped payload `toDbTask` produces for a write. Deliberately PARTIAL: `undefined`
 * means "leave this column alone", which is how an update patch avoids clobbering columns
 * it does not mention (notably `links`).
 * @typedef {Partial<TaskRow>} TaskWrite
 */

/* ---------------------------------------------------------------------------------
   PROJECTS
--------------------------------------------------------------------------------- */

/**
 * `public.projects` as PostgREST returns it.
 * @typedef {object} ProjectRow
 * @property {ProjectId} id
 * @property {Uuid} workspace_id               NOT NULL since Phase 3A.
 * @property {string} name                     NOT NULL.
 * @property {string} color                    NOT NULL, default '#64748b'.
 * @property {string} icon                     NOT NULL, default '◇'.
 * @property {Uuid | null} created_by          Nullable FK to auth.users.
 * @property {IsoTimestamp} created_at         NOT NULL.
 */

/**
 * @typedef {object} Project
 * @property {ProjectId} id
 * @property {string} name
 * @property {string | null} color
 * @property {string | null} icon
 * @property {Uuid} [workspaceId]
 */

/**
 * How `projects.deleteViaRpc` disposes of the tasks filed under a project being deleted.
 * These are the literals the `delete_project` RPC actually accepts — anything else raises
 * `22023 invalid mode`.
 *  - `unassign` (owner+admin, rank>=2) re-files the tasks onto `reassignTo`, which MUST
 *    resolve to a real project or they are silently unfiled — the data-loss path closed by
 *    migration 20260719172122, which now raises P0002 instead.
 *  - `cascade` (OWNER only, rank 3) deletes the caller-visible tasks.
 * @typedef {'cascade' | 'unassign'} ProjectDeleteMode
 */

/* ---------------------------------------------------------------------------------
   MEMBERS / WORKSPACES / ROLES
--------------------------------------------------------------------------------- */

/**
 * `public.members` — the PROFILE table. `role` here is VESTIGIAL; never read it for authz.
 * `avatar_url` stores a storage PATH (not a URL) since the private-bucket conversion, and
 * is pinned by trigger to the row owner's own uid folder.
 * @typedef {object} MemberRow
 * @property {Uuid} id                         = the auth user id.
 * @property {string} email
 * @property {string | null} display_name
 * @property {string} role                     NOT NULL, and its CHECK is `('owner','member')`
 *   ONLY — so this column can never even hold 'admin' or 'guest'. Vestigial; the authority is
 *   `workspace_members.role`. Never read this for authorization.
 * @property {string | null} avatar_url        A storage PATH, e.g. "<uid>/abc123.jpg".
 * @property {string | null} bio
 * @property {string | null} status_text
 * @property {string | null} status_emoji
 * @property {IsoTimestamp} created_at
 */

/**
 * A workspace member with profile, as `workspace_members_list` RPC returns them.
 * @typedef {object} WorkspaceMember
 * @property {Uuid} userId
 * @property {string | null} displayName
 * @property {string} email
 * @property {Role} role
 * @property {string | null} [avatarUrl]
 * @property {string | null} [bio]
 * @property {string | null} [statusText]
 * @property {string | null} [statusEmoji]
 */

/**
 * The caller's own membership row — the authority for role gating in the client.
 * @typedef {object} Membership
 * @property {Uuid} workspaceId
 * @property {Role} role
 */

/**
 * @typedef {object} Workspace
 * @property {Uuid} id
 * @property {string} name                     NOT NULL.
 * @property {Uuid | null} [owner_id]          Nullable (on delete set null). NOT what authorizes
 *   anything — `workspace_members.role` is. `workspaces.listMine()` does not select it.
 * @property {string | null} slug              Nullable; added later and backfilled.
 * @property {IsoTimestamp} created_at         NOT NULL.
 */

/**
 * The profile columns a user may write on their OWN row. `display_name` is the only one
 * covered by the base column grant; the rest are validated server-side by
 * `members_validate_profile`. Identity columns (id/email/created_at/role) are immutable —
 * the `members_lock_identity` trigger raises 42501.
 * @typedef {object} ProfilePatch
 * @property {string} [displayName]
 * @property {string} [statusText]
 * @property {string} [statusEmoji]
 * @property {string} [bio]
 * @property {string | null} [avatarUrl]       A storage PATH in your own uid folder, or null.
 */

/* ---------------------------------------------------------------------------------
   INVITATIONS
--------------------------------------------------------------------------------- */

/**
 * @typedef {object} Invitation
 * @property {Uuid} id
 * @property {Uuid} workspace_id               NOT NULL.
 * @property {string} email                    NOT NULL. The invite is EMAIL-BOUND.
 * @property {Role} role                       NOT NULL. The CHECK allows all four, but
 *   `create_invitation` validates to 'member' | 'guest' only — owner/admin are granted after
 *   join via `set_member_role`.
 * @property {Uuid} token                      NOT NULL unique — the value in `/invite/:token`.
 * @property {InvitationStatus} status         NOT NULL, default 'pending'.
 * @property {Uuid} invited_by                 NOT NULL.
 * @property {IsoTimestamp} created_at         NOT NULL.
 * @property {IsoTimestamp} expires_at         NOT NULL, default now() + 14 days. Expiry is
 *   THIS passing, not a status value — see InvitationStatus.
 * @property {IsoTimestamp | null} accepted_at
 * @property {Uuid | null} accepted_by
 */

/* ---------------------------------------------------------------------------------
   NOTIFICATIONS / COMMENTS
--------------------------------------------------------------------------------- */

/**
 * `notifications.type` has NO CHECK constraint in the DB, so this union is the app's
 * documented set rather than an enforced one. Treat an unknown value as displayable.
 * @typedef {'task_assigned' | 'comment_added' | 'task_completed' | 'mention' | 'due_soon' | 'overdue' | 'dm_received' | string} NotificationType
 */

/**
 * @typedef {object} NotificationRow
 * @property {Uuid} id
 * @property {Uuid | null} workspace_id        Nullable by design; recipient_id is the real gate.
 * @property {Uuid} recipient_id
 * @property {Uuid | null} actor_id
 * @property {TaskId | null} task_id           TEXT FK to tasks.id — not a uuid.
 * @property {string | null} ref_id            Polymorphic (e.g. a DM conversation id).
 * @property {NotificationType} type          NOT NULL.
 * @property {string | null} title             NULLABLE — the bell renders `message`, not this.
 * @property {string} message                  NOT NULL. This is what the UI actually draws.
 * @property {boolean} read                    NOT NULL, default false.
 * @property {IsoTimestamp} created_at         NOT NULL.
 */

/**
 * @typedef {object} Notification
 * @property {Uuid} id
 * @property {Uuid | null} workspaceId
 * @property {Uuid} recipientId
 * @property {Uuid | null} actorId
 * @property {TaskId | null} taskId
 * @property {string | null} refId
 * @property {NotificationType} type
 * @property {string | null} title             Nullable — see NotificationRow.title.
 * @property {string} message                  What the bell renders.
 * @property {boolean} read
 * @property {IsoTimestamp} createdAt
 */

/**
 * @typedef {object} CommentRow
 * @property {Uuid} id
 * @property {Uuid} workspace_id               NOT NULL since Phase 2.
 * @property {TaskId} task_id                  NOT NULL. TEXT FK — not a uuid.
 * @property {Uuid | null} author_id           NULLABLE — `on delete set null`. A departed
 *   member's comments survive with no author; render a fallback, never assume a name.
 * @property {string} body                     NOT NULL.
 * @property {Uuid[]} mentions                 NOT NULL, default '{}'.
 * @property {IsoTimestamp} created_at         NOT NULL.
 * @property {IsoTimestamp} updated_at         NOT NULL.
 */

/**
 * @typedef {object} Comment
 * @property {Uuid} id
 * @property {Uuid} workspaceId
 * @property {TaskId} taskId
 * @property {Uuid | null} authorId           Nullable — see CommentRow.author_id.
 * @property {string} body
 * @property {Uuid[]} mentions
 * @property {IsoTimestamp} createdAt
 * @property {IsoTimestamp} updatedAt
 */

/* ---------------------------------------------------------------------------------
   MESSAGES (team chat) + DIRECT MESSAGES
--------------------------------------------------------------------------------- */

/**
 * `public.messages`. `sender_id` is NULLABLE — a departed member's messages survive with a
 * null sender, and code that filters senders must use `is distinct from` semantics or it
 * silently drops them (the bug fixed in the 2026-07-19 chat pass).
 * @typedef {object} MessageRow
 * @property {Uuid} id
 * @property {Uuid} workspace_id
 * @property {Uuid | null} sender_id
 * @property {string | null} body
 * @property {string | null} audio_path
 * @property {number | null} audio_duration_seconds
 * @property {Uuid[]} mentions                 NOT NULL, default '{}'.
 * @property {IsoTimestamp} created_at         NOT NULL.
 * @property {IsoTimestamp} updated_at         NOT NULL.
 * @property {IsoTimestamp | null} edited_at   Non-null once edited → drives "(edited)".
 * @property {IsoTimestamp | null} deleted_at  Non-null = tombstone, content stripped server-side.
 */

/**
 * @typedef {object} Message
 * @property {Uuid} id
 * @property {Uuid} workspaceId
 * @property {Uuid | null} senderId
 * @property {string | null} body
 * @property {string | null} audioPath
 * @property {number | null} audioDuration
 * @property {Uuid[]} mentions
 * @property {IsoTimestamp} createdAt
 * @property {IsoTimestamp | null} updatedAt
 * @property {IsoTimestamp | null} editedAt
 * @property {IsoTimestamp | null} deletedAt
 */

/**
 * @typedef {object} DmConversation
 * @property {Uuid} id
 * @property {Uuid} workspaceId
 * @property {Uuid} userLo
 * @property {Uuid} userHi
 * @property {IsoTimestamp} createdAt
 */

/**
 * @typedef {object} DirectMessage
 * @property {Uuid} id
 * @property {Uuid} conversationId
 * @property {Uuid} workspaceId
 * @property {Uuid | null} senderId
 * @property {string | null} body
 * @property {string | null} audioPath
 * @property {number | null} audioDuration
 * @property {IsoTimestamp} createdAt
 * @property {IsoTimestamp | null} updatedAt
 * @property {IsoTimestamp | null} editedAt
 * @property {IsoTimestamp | null} deletedAt
 */

/**
 * A read cursor row from `chat_reads` / `dm_reads`. The cursor is MONOTONIC — the DB
 * triggers reject moving it backwards or into the future.
 * @typedef {object} ReadCursor
 * @property {Uuid} userId
 * @property {IsoTimestamp} lastReadAt
 */

/* ---------------------------------------------------------------------------------
   TASK ATTACHMENTS
--------------------------------------------------------------------------------- */

/**
 * @typedef {object} AttachmentRow
 * @property {Uuid} id
 * @property {TaskId} task_id                  TEXT FK — not a uuid.
 * @property {Uuid} workspace_id
 * @property {Uuid | null} uploaded_by         NULLABLE — `on delete set null`. Reachable and
 *   renderable: attachment DELETE is "uploader-own or admin+", so an orphaned upload persists.
 * @property {string} storage_path
 * @property {string} filename
 * @property {string | null} mime_type
 * @property {number | null} size_bytes
 * @property {IsoTimestamp} created_at
 */

/**
 * @typedef {object} Attachment
 * @property {Uuid} id
 * @property {TaskId} taskId
 * @property {Uuid} workspaceId
 * @property {Uuid | null} uploadedBy          Nullable — see AttachmentRow.uploaded_by.
 * @property {string} storagePath
 * @property {string} filename
 * @property {string | null} mimeType
 * @property {number | null} sizeBytes
 * @property {IsoTimestamp} createdAt
 */

/* ---------------------------------------------------------------------------------
   REALTIME
--------------------------------------------------------------------------------- */

/**
 * A realtime change event as the app's subscribe() callbacks surface it.
 * NOTE the documented asymmetry: `tasks` is REPLICA IDENTITY DEFAULT, so on DELETE the
 * old row carries ONLY the primary key — every other field is absent. `messages` and
 * `comments` are REPLICA IDENTITY FULL and carry the whole old row.
 * @template T
 * @typedef {object} RealtimeChange
 * @property {'INSERT' | 'UPDATE' | 'DELETE'} eventType
 * @property {T | Record<string, unknown>} [new]
 * @property {T | Partial<T> | Record<string, unknown>} [old]
 */

/**
 * What this app tracks on a Realtime Presence channel. supabase-js types `presenceState()`
 * entries as `{ presence_ref: string }` because the tracked payload is user-defined, so the
 * fields below are invisible to it — they are whatever `channel.track()` was handed. Keep
 * this in sync with the object passed to `track()` in `messages.presence`.
 *
 * SECURITY NOTE: presence is a PUBLIC broadcast channel. Everything here is spoofable and
 * readable by anyone who knows the channel key — which is why the channel key must be
 * tenant-scoped and why only metadata (never message content) travels this way. This is the
 * accepted residual documented in the security audits.
 *
 * @typedef {object} PresenceMeta
 * @property {Uuid} [userId]
 * @property {string} [name]
 * @property {boolean} [typing]
 * @property {boolean} [recording]
 * @property {IsoTimestamp | null} [readAt]
 * @property {string} [presence_ref]
 */

/** An unsubscribe function returned by every subscribe() helper. Always call it on unmount. */
/** @typedef {() => void} Unsubscribe */

export {};
